language: 
  - python

python:
  - "3.5"

before_install:
  - git submodule update --remote

install:
  - pip install flake8
  - pip install -r requirements.txt
  - python setup.py install

script: 
  - py.test

after_success:
  - flake8 .

notifications:
  email: false
