language: 
  - python

python:
  - "3.4"

before_install:
  - git submodule update --remote

install:
  - pip install flake8
  - pip install -r requirements.txt

script: 
  - py.test

after_success:
  - flake8 --max-line-length 100 .

notifications:
  email: false
